### ISSUE TITLE
How to change Normal highlight of window ?

### ISSUE THREAD

**Issue by Nguyen-Hoang-Nam** [Xuyuanp/yanil#3]
I want to change the background of yanil window but I don't know how, I try winhighlight=Normal:... but it didn't worked.

Moreover, there are less options than nvim-tree so I must change source code to make it works such as show window in right, change root node name, ellipsis.

There are still some things I can't  implement such as directory with only one subdirectory and no file may corrupt to directory/subdirectrory > instead of directory > subdirectory > (Java often has this kind of directories).

![yanil](https://user-images.githubusercontent.com/74345759/131206656-80da0ef4-e93c-411e-81b2-43b3849d057f.jpg)

**Comment by Xuyuanp** [comment]
Sorry for inconvenient. I'm planning refactor this plugin to make it more configurable. But things in real life trouble me a lot, I don't have much time in several months. 

for your questions, using `winhighlight` should be able to set background of yanil window.

```vim
hi MyNormal guifg=#xxxxxx guibg=#xxxxxx
set winhighlight=Normal:MyNormal
```
