### ISSUE TITLE
`node.toggle()` not working to open/close directories

### ISSUE THREAD

**Issue by pwntester** [Xuyuanp/yanil#5]
Hi,

Im trying to create a mapping (`o`) that behaves in the following way. When used on a directory it collapses or opens it depending on whether it is opened or closed. If used on a file, then it will close the directory that contains that file. I tried the following code but its not doing anything. Can you please help understand why its not working?

```lua
    ["o"] = function(tree, node)
      node = node:is_dir() and node or node.parent
      node:toggle()
      tree:force_refresh_node()
    end
```

Thanks!

**Comment by Xuyuanp** [comment]
```lua
['o'] = function(tree, node)
    node = node:is_dir() and node or node.parent

    tree:refresh(node, {}, function()
        node:toggle()
    end)

    tree:go_to_node(node) -- move cursor. (not necessary)
end,
```

You shouldn't just toggle a node, because the tree has no idea what happened.

**Comment by pwntester** [comment]
Works great, thanks!
